name: Pull wasm builds

on:
  schedule:
    - cron: '40 */12 * * *'
  workflow_dispatch: {}

jobs:
  pull-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - uses: actions/github-script@v7
        with:
          script: |
            const { default: run } = await import('${{ github.workspace }}/pull.js')

            await run({github})
